version: '3'
services:
  db:
    image: postgres:14-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes: 
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
